name: medico

description: Medico Healthcare App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  cached_network_image: ^3.3.1

  # QR + ML
  qr_flutter: ^4.1.0
  google_mlkit_text_recognition: ^0.11.0

  # File Picker
  file_picker: ^8.0.0+1

  # Networking
  http: ^1.2.1
  dio: ^5.4.0
  socket_io_client: ^2.0.0

  # Local Storage
  shared_preferences: ^2.2.3

  # Location
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # URL Launcher
  url_launcher: ^6.2.5

  # WebView
  webview_flutter: ^4.7.0

  # Image
  image_picker: ^1.1.2

  # Permissions
  permission_handler: ^11.3.1

  # FIREBASE
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:

  android: true

  ios: true

  image_path: assets/logo.png

  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:

    - assets/logo.png

    - assets/cashfree.png