name: medico
description: Medico Healthcare App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  pdf: ^3.11.1
  printing: ^5.13.2

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  cached_network_image: ^3.3.1

  # Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5

  # QR & ML
  qr_flutter: ^4.1.0
  google_mlkit_text_recognition: ^0.11.0

  # File Handling
  file_picker: ^8.0.0+1
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  mime: ^1.0.5
  http_parser: ^4.0.2

  # Networking
  http: ^1.2.1
  dio: ^5.4.0
  socket_io_client: ^2.0.0

  # Location & Maps
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # WebView
  webview_flutter: ^4.7.0

  # Permissions & Security
  permission_handler: ^11.3.1
  screen_protector: ^1.4.2

  # Firebase
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.1

  # Payment
  flutter_cashfree_pg_sdk: ^2.4.0+52

  # Utilities
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/cashfree.png